//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanoramaIMCCalculator.Resources.AppResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PanoramaIMCCalculator.Resources.AppResources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMC Calculator ne collecte aucune information vous concernant..
        /// </summary>
        public static string AProposAucuneInformationCollecteeText {
            get {
                return ResourceManager.GetString("AProposAucuneInformationCollecteeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to par Rémi Lavedrine.
        /// </summary>
        public static string AProposAuthor {
            get {
                return ResourceManager.GetString("AProposAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donner votre avis.
        /// </summary>
        public static string AProposDonnerVotreAvisText {
            get {
                return ResourceManager.GetString("AProposDonnerVotreAvisText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyer vos commentaires, questions, louanges à :.
        /// </summary>
        public static string AProposEnvoyerCommentairesText {
            get {
                return ResourceManager.GetString("AProposEnvoyerCommentairesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMC Calculator ne peut être tenu pour responsable de la mauvaise utilisation que vous pouvez faire des données fournies..
        /// </summary>
        public static string AProposNonResponsableText {
            get {
                return ResourceManager.GetString("AProposNonResponsableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to à propos.
        /// </summary>
        public static string AProposPanoramaAProposTitle {
            get {
                return ResourceManager.GetString("AProposPanoramaAProposTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to legalese.
        /// </summary>
        public static string AProposPanoramaLegaleseTitle {
            get {
                return ResourceManager.GetString("AProposPanoramaLegaleseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nouveautés.
        /// </summary>
        public static string AProposPanoramaNouveautesTitle {
            get {
                return ResourceManager.GetString("AProposPanoramaNouveautesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to à propos.
        /// </summary>
        public static string AProposText {
            get {
                return ResourceManager.GetString("AProposText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to merci à.
        /// </summary>
        public static string AProposThanksTo {
            get {
                return ResourceManager.GetString("AProposThanksTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version 1.0.
        /// </summary>
        public static string AProposVersion10 {
            get {
                return ResourceManager.GetString("AProposVersion10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Première version de l&apos;application.
        /// </summary>
        public static string AProposVersion10Content {
            get {
                return ResourceManager.GetString("AProposVersion10Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version 1.1.
        /// </summary>
        public static string AProposVersion11 {
            get {
                return ResourceManager.GetString("AProposVersion11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajout du Live Tile lors du calcul de l&apos;IMC et gestion des images et du calcul lorsque l&apos;utilisateur est un homme ou une femme..
        /// </summary>
        public static string AProposVersion11Content {
            get {
                return ResourceManager.GetString("AProposVersion11Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version 1.3.
        /// </summary>
        public static string AProposVersion13 {
            get {
                return ResourceManager.GetString("AProposVersion13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajout de la partie about et correction d&apos;un bug dans le calcul de l&apos;imc pour certaines valeurs d&apos;imc et de la non correspondance de la bonne image sur la live tile..
        /// </summary>
        public static string AProposVersion13Content {
            get {
                return ResourceManager.GetString("AProposVersion13Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vie privée.
        /// </summary>
        public static string AProposViePriveeText {
            get {
                return ResourceManager.GetString("AProposViePriveeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculer.
        /// </summary>
        public static string CalculateIMCButtonText {
            get {
                return ResourceManager.GetString("CalculateIMCButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calcul.
        /// </summary>
        public static string CalculPanoramaItemTitle {
            get {
                return ResourceManager.GetString("CalculPanoramaItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dénutrition : 
        ///La dénutrition est un état pathologique résultant d&apos;apports nutritionnels insuffisants en regard des dépenses énergétiques de l&apos;organisme. Lorsque les apports sont inadaptés en plus d&apos;être insuffisants, on parle de malnutrition.
        ///La dénutrition est classée dans la section marasme nutritionnel de la classification internationale des maladies.
        ///
        ///Physiopathologie
        ///La dénutrition peut avoir de multiple origines. L&apos;étiologie en est variée et peut associer une affection organique, psychiatrique o [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DenutritionDetailPageContent {
            get {
                return ResourceManager.GetString("DenutritionDetailPageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dénutrition.
        /// </summary>
        public static string DenutritionDetailPageTitle {
            get {
                return ResourceManager.GetString("DenutritionDetailPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes dans la zone de dénutrition..
        /// </summary>
        public static string DenutritionHubTileMessage {
            get {
                return ResourceManager.GetString("DenutritionHubTileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dénutrition.
        /// </summary>
        public static string DenutritionHubTileTitle {
            get {
                return ResourceManager.GetString("DenutritionHubTileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un problème est survenu lors du calcul de votre IMC.
        ///Veuillez entrer à nouveau votre taille et votre poids..
        /// </summary>
        public static string IMCCalculationError {
            get {
                return ResourceManager.GetString("IMCCalculationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre IMC est de .
        /// </summary>
        public static string IMCResultTextFirstPart {
            get {
                return ResourceManager.GetString("IMCResultTextFirstPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string IMCResultTextSecondPart {
            get {
                return ResourceManager.GetString("IMCResultTextSecondPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes dans la zone de dénutrition..
        /// </summary>
        public static string InfoFromDenutritionIMC {
            get {
                return ResourceManager.GetString("InfoFromDenutritionIMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes dans la zone de maigreur..
        /// </summary>
        public static string InfoFromMaigreurIMC {
            get {
                return ResourceManager.GetString("InfoFromMaigreurIMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes dans la zone normale..
        /// </summary>
        public static string InfoFromNormalIMC {
            get {
                return ResourceManager.GetString("InfoFromNormalIMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes dans la zone d&apos;obésité modérée..
        /// </summary>
        public static string InfoFromObesiteIMC {
            get {
                return ResourceManager.GetString("InfoFromObesiteIMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes dans la zone d&apos;obésité sévère..
        /// </summary>
        public static string InfoFromObesiteSevereIMC {
            get {
                return ResourceManager.GetString("InfoFromObesiteSevereIMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes dans la zone de surpoids..
        /// </summary>
        public static string InfoFromSurpoidsIMC {
            get {
                return ResourceManager.GetString("InfoFromSurpoidsIMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to informations.
        /// </summary>
        public static string InformationsPanoramaItemTitle {
            get {
                return ResourceManager.GetString("InformationsPanoramaItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne changez rien..
        /// </summary>
        public static string LiveTileBackTitleNormal {
            get {
                return ResourceManager.GetString("LiveTileBackTitleNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maigreur :
        ///
        ///La maigreur est l&apos;état de ce qui est maigre. Dans le cas d&apos;une personne, on parle d&apos;insuffisance pondérale. À ce titre, elle est définie par l&apos;Organisation mondiale de la santé comme la condition anormale des individus dont l&apos;indice de masse corporelle est comprise entre 15 et 18,5.
        ///La maigreur pathologique augmente le risque de maladies diverses parmi lesquelles on peut citer les infections ou l&apos;ostéoporose mais peut également être le symptôme de l&apos;une d&apos;elles. Elle peut être également un ét [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MaigreurDetailPageContent {
            get {
                return ResourceManager.GetString("MaigreurDetailPageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maigreur.
        /// </summary>
        public static string MaigreurDetailPageTitle {
            get {
                return ResourceManager.GetString("MaigreurDetailPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes dans la zone de maigreur..
        /// </summary>
        public static string MaigreurHubTileMessage {
            get {
                return ResourceManager.GetString("MaigreurHubTileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maigreur.
        /// </summary>
        public static string MaigreurHubTileTitle {
            get {
                return ResourceManager.GetString("MaigreurHubTileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taille.
        /// </summary>
        public static string metricHeightTextBoxText {
            get {
                return ResourceManager.GetString("metricHeightTextBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculer votre IMC..
        /// </summary>
        public static string MetricIMCResultTextBlock {
            get {
                return ResourceManager.GetString("MetricIMCResultTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poids.
        /// </summary>
        public static string metricWeightTextBoxText {
            get {
                return ResourceManager.GetString("metricWeightTextBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il ne faut pas confondre la masse (grave) et le poids.
        ///Le poids d&apos;un corps est une force, due principalement à l&apos;action qu&apos;exerce sur lui le champ gravitationnel.
        ///
        ///Réserves à l&apos;égard de l&apos;IMC
        ///Il est important de garder à l’esprit que l’IMC n’est qu’un indicateur, non pas une donnée absolue. Du fait de leur masse musculaire, certains sportifs ont un indice de masse corporelle supérieur à 25 kg/m2, sans qu’ils encourent de danger. De plus, selon la morphologie d’une personne, son IMC de bonne forme varie. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NormalDetailPageContent {
            get {
                return ResourceManager.GetString("NormalDetailPageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string NormalDetailPageTitle {
            get {
                return ResourceManager.GetString("NormalDetailPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous etes dans la zone normale. Bravo!!.
        /// </summary>
        public static string NormalHubTileMessage {
            get {
                return ResourceManager.GetString("NormalHubTileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string NormalHubTileTitle {
            get {
                return ResourceManager.GetString("NormalHubTileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;obésité est l&apos;état d&apos;un individu ayant une masse corporelle largement supérieure à ce qui est souhaitable ou acceptable, généralement dû à une accumulation de masse adipeuse. L&apos;obésité humaine a été reconnue comme une maladie en 1997 par l&apos;OMS. Cette organisation définit « le surpoids et l&apos;obésité comme une accumulation anormale ou excessive de graisse corporelle qui peut nuire à la santé ». Sa prévention est un problème de santé publique dans les pays développés. Elle peut avoir des répercussions importa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ObesiteDetailPageContent {
            get {
                return ResourceManager.GetString("ObesiteDetailPageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obésité.
        /// </summary>
        public static string ObesiteDetailPageTitle {
            get {
                return ResourceManager.GetString("ObesiteDetailPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes dans la zone d&apos;obésité modérée.
        /// </summary>
        public static string ObesiteHubTileMessage {
            get {
                return ResourceManager.GetString("ObesiteHubTileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obésité.
        /// </summary>
        public static string ObesiteHubTileTitle {
            get {
                return ResourceManager.GetString("ObesiteHubTileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;obésité est l&apos;état d&apos;un individu ayant une masse corporelle largement supérieure à ce qui est souhaitable ou acceptable, généralement dû à une accumulation de masse adipeuse. L&apos;obésité humaine a été reconnue comme une maladie en 1997 par l&apos;OMS. Cette organisation définit « le surpoids et l&apos;obésité comme une accumulation anormale ou excessive de graisse corporelle qui peut nuire à la santé ». Sa prévention est un problème de santé publique dans les pays développés. Elle peut avoir des répercussions importa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ObesiteSevereDetailPageContent {
            get {
                return ResourceManager.GetString("ObesiteSevereDetailPageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obésité sévère.
        /// </summary>
        public static string ObesiteSevereDetailPageTitle {
            get {
                return ResourceManager.GetString("ObesiteSevereDetailPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes dans la zone d&apos;obésité sévère..
        /// </summary>
        public static string ObesiteSevereHubTileMessage {
            get {
                return ResourceManager.GetString("ObesiteSevereHubTileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obésité sévère.
        /// </summary>
        public static string ObesiteSevereHubTileTitle {
            get {
                return ResourceManager.GetString("ObesiteSevereHubTileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculer votre IMC.
        /// </summary>
        public static string PanoramaTitle {
            get {
                return ResourceManager.GetString("PanoramaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to résumé.
        /// </summary>
        public static string ResumePanoramaItemTitle {
            get {
                return ResourceManager.GetString("ResumePanoramaItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poids.
        /// </summary>
        public static string ResumePoidsText {
            get {
                return ResourceManager.GetString("ResumePoidsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taille.
        /// </summary>
        public static string ResumeTailleText {
            get {
                return ResourceManager.GetString("ResumeTailleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dénutrition.
        /// </summary>
        public static string StackPanelDenutritionTitle {
            get {
                return ResourceManager.GetString("StackPanelDenutritionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes dans la zone de dénutrition.
        /// </summary>
        public static string StackPanelDenutritionZoneInfoText {
            get {
                return ResourceManager.GetString("StackPanelDenutritionZoneInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moins de 16.5.
        /// </summary>
        public static string StackPanelDenutritionZoneText {
            get {
                return ResourceManager.GetString("StackPanelDenutritionZoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maigreur.
        /// </summary>
        public static string StackPanelMaigreurTitle {
            get {
                return ResourceManager.GetString("StackPanelMaigreurTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes dans la zone de maigreur.
        /// </summary>
        public static string StackPanelMaigreurZoneInfoText {
            get {
                return ResourceManager.GetString("StackPanelMaigreurZoneInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de 16.5 à 18.5.
        /// </summary>
        public static string StackPanelMaigreurZoneText {
            get {
                return ResourceManager.GetString("StackPanelMaigreurZoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string StackPanelNormalTitle {
            get {
                return ResourceManager.GetString("StackPanelNormalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de 18.5 à 25.
        /// </summary>
        public static string StackPanelNormalZoneText {
            get {
                return ResourceManager.GetString("StackPanelNormalZoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obésité sévère.
        /// </summary>
        public static string StackPanelObesiteSevereTitle {
            get {
                return ResourceManager.GetString("StackPanelObesiteSevereTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes dans la zone d&apos;obésité sévère.
        /// </summary>
        public static string StackPanelObesiteSevereZoneInfoText {
            get {
                return ResourceManager.GetString("StackPanelObesiteSevereZoneInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35 et plus.
        /// </summary>
        public static string StackPanelObesiteSevereZoneText {
            get {
                return ResourceManager.GetString("StackPanelObesiteSevereZoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obésité modérée.
        /// </summary>
        public static string StackPanelObesiteTitle {
            get {
                return ResourceManager.GetString("StackPanelObesiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes dans la zone d&apos;obésité modérée.
        /// </summary>
        public static string StackPanelObesiteZoneInfoText {
            get {
                return ResourceManager.GetString("StackPanelObesiteZoneInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de 30 à 35.
        /// </summary>
        public static string StackPanelObesiteZoneText {
            get {
                return ResourceManager.GetString("StackPanelObesiteZoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surpoids.
        /// </summary>
        public static string StackPanelSurpoidsTitle {
            get {
                return ResourceManager.GetString("StackPanelSurpoidsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes dans la zone de surpoids.
        /// </summary>
        public static string StackPanelSurpoidsZoneInfoText {
            get {
                return ResourceManager.GetString("StackPanelSurpoidsZoneInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de 25 à 30.
        /// </summary>
        public static string StackPanelSurpoidsZoneText {
            get {
                return ResourceManager.GetString("StackPanelSurpoidsZoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le surpoids est l&apos;état d&apos;une personne présentant une corpulence considérée comme légèrement plus importante que la normale ou la moyenne dans une société donnée.
        ///
        ///Il est définie par l&apos;Organisation mondiale de la santé comme l&apos;attribut des individus présentant un indice de masse corporelle compris entre 25 et 30 kilogrammes par mètres carrés et est, selon ces critères, bornée par la minceur (ou corpulence normale) et l&apos;obésité modérée.
        ///
        ///Credits Wikipedia : http://fr.wikipedia.org/wiki/Surpoids.
        /// </summary>
        public static string SurpoidsDetailPageContent {
            get {
                return ResourceManager.GetString("SurpoidsDetailPageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surpoids.
        /// </summary>
        public static string SurpoidsDetailPageTitle {
            get {
                return ResourceManager.GetString("SurpoidsDetailPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes dans la zone de surpoids..
        /// </summary>
        public static string SurpoidsHubTileMessage {
            get {
                return ResourceManager.GetString("SurpoidsHubTileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surpoids.
        /// </summary>
        public static string SurpoidsHubTileTitle {
            get {
                return ResourceManager.GetString("SurpoidsHubTileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gagnez .
        /// </summary>
        public static string WeightToGainFirstPart {
            get {
                return ResourceManager.GetString("WeightToGainFirstPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  kilos..
        /// </summary>
        public static string WeightToGainLastPart {
            get {
                return ResourceManager.GetString("WeightToGainLastPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perdez.
        /// </summary>
        public static string WeightToLoseFirstPart {
            get {
                return ResourceManager.GetString("WeightToLoseFirstPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  kilos..
        /// </summary>
        public static string WeightToLoseLastPart {
            get {
                return ResourceManager.GetString("WeightToLoseLastPart", resourceCulture);
            }
        }
    }
}
